/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.DepartamentoCtrl;
import javax.swing.JOptionPane;

/**
 *
 * @author Yeni
 */
public class DepartamentosView extends javax.swing.JPanel {

    /** Creates new form DepartamentosView */
    DepartamentoCtrl departamentoCtrl;
    public DepartamentosView() {
        departamentoCtrl = new DepartamentoCtrl();
        initComponents();
        lstDepartamentos.setModel(departamentoCtrl.getModel());
        lstDepartamentos.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreDepartamento = new javax.swing.JTextField();
        btnNuevoDepartamento = new javax.swing.JButton();
        btnAdicionarDepartamento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDepartamentos = new javax.swing.JList<>();
        btnEditarDepartamento = new javax.swing.JButton();
        btnModificarDepartamento = new javax.swing.JButton();
        btnGuardarDepartamento = new javax.swing.JButton();
        btnEliminarDepartamento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIdDepartamento = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(414, 423));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Nombre: ");

        txtNombreDepartamento.setEnabled(false);

        btnNuevoDepartamento.setText("Nuevo");
        btnNuevoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoDepartamentoActionPerformed(evt);
            }
        });

        btnAdicionarDepartamento.setText("Adicionar");
        btnAdicionarDepartamento.setEnabled(false);
        btnAdicionarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarDepartamentoActionPerformed(evt);
            }
        });

        lstDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDepartamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstDepartamentos);

        btnEditarDepartamento.setText("Editar");
        btnEditarDepartamento.setEnabled(false);
        btnEditarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDepartamentoActionPerformed(evt);
            }
        });

        btnModificarDepartamento.setText("Modificar");
        btnModificarDepartamento.setEnabled(false);
        btnModificarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDepartamentoActionPerformed(evt);
            }
        });

        btnGuardarDepartamento.setText("Guardar");
        btnGuardarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDepartamentoActionPerformed(evt);
            }
        });

        btnEliminarDepartamento.setText("Eliminar");
        btnEliminarDepartamento.setEnabled(false);
        btnEliminarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDepartamentoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("id: ");

        txtIdDepartamento.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtIdDepartamento))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                            .addComponent(btnNuevoDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdicionarDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnEliminarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnGuardarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txtNombreDepartamento)
                    .addComponent(btnNuevoDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdDepartamento)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(btnAdicionarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarDepartamento)
                            .addComponent(btnModificarDepartamento))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarDepartamento))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDepartamentoActionPerformed
        txtNombreDepartamento.setText("");
        txtIdDepartamento.setText("");
        txtNombreDepartamento.setEnabled(true);
        txtIdDepartamento.setEnabled(true);
        btnNuevoDepartamento.setEnabled(false);
        btnAdicionarDepartamento.setEnabled(true);
    }//GEN-LAST:event_btnNuevoDepartamentoActionPerformed

    private void btnAdicionarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarDepartamentoActionPerformed
        departamentoCtrl.adicionarDepatamento(Integer.parseInt(txtIdDepartamento.getText()),txtNombreDepartamento.getText());
        JOptionPane.showMessageDialog(this, "Departamento adicionado con exito.");
        txtNombreDepartamento.setEnabled(false);
        txtIdDepartamento.setEnabled(false);
        txtIdDepartamento.setText("");
        txtNombreDepartamento.setText("");
        btnNuevoDepartamento.setEnabled(true);
        btnAdicionarDepartamento.setEnabled(false);
        listarDepartamentos();
    }//GEN-LAST:event_btnAdicionarDepartamentoActionPerformed

    private void lstDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDepartamentosMouseClicked
        btnEditarDepartamento.setEnabled(true);
        btnEliminarDepartamento.setEnabled(true);
        txtNombreDepartamento.setText(departamentoCtrl.getDepartamento(lstDepartamentos.getSelectedIndex()).getNombre());
        txtIdDepartamento.setText(String.valueOf(departamentoCtrl.getDepartamento(lstDepartamentos.getSelectedIndex()).getId()));
       // listarDepartamentos();
    }//GEN-LAST:event_lstDepartamentosMouseClicked

    private void btnEditarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDepartamentoActionPerformed
        btnEditarDepartamento.setEnabled(false);
        btnModificarDepartamento.setEnabled(true);
        txtNombreDepartamento.setEnabled(true);
        txtIdDepartamento.setEnabled(true);
    }//GEN-LAST:event_btnEditarDepartamentoActionPerformed

    private void btnModificarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDepartamentoActionPerformed
        txtNombreDepartamento.setEnabled(true);
        departamentoCtrl.modificarDepartamento(Integer.parseInt(txtIdDepartamento.getText()),txtNombreDepartamento.getText());
        JOptionPane.showMessageDialog(this, "Departamento guardado con exito.");
        btnModificarDepartamento.setEnabled(false);
        listarDepartamentos();
    }//GEN-LAST:event_btnModificarDepartamentoActionPerformed

    private void btnEliminarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDepartamentoActionPerformed
        departamentoCtrl.eliminarDepartamento(lstDepartamentos.getSelectedIndex());
        JOptionPane.showMessageDialog(this, "Departamento eliminado.");
        txtNombreDepartamento.setText("");
        listarDepartamentos();
    }//GEN-LAST:event_btnEliminarDepartamentoActionPerformed

    private void btnGuardarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDepartamentoActionPerformed
        departamentoCtrl.guardarDepartamentos();
        JOptionPane.showMessageDialog(this, "Departamentos guardados con exito.");
    }//GEN-LAST:event_btnGuardarDepartamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarDepartamento;
    private javax.swing.JButton btnEditarDepartamento;
    private javax.swing.JButton btnEliminarDepartamento;
    private javax.swing.JButton btnGuardarDepartamento;
    private javax.swing.JButton btnModificarDepartamento;
    private javax.swing.JButton btnNuevoDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstDepartamentos;
    private javax.swing.JTextField txtIdDepartamento;
    private javax.swing.JTextField txtNombreDepartamento;
    // End of variables declaration//GEN-END:variables

    private void listarDepartamentos() {
        lstDepartamentos.setModel(departamentoCtrl.getModel());
        lstDepartamentos.updateUI();
    }

}
