/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author P201
 */
public class Principal extends javax.swing.JFrame {
    
    EmpleadosView empleadosView;
    DepartamentosView departamentosView;
    ConsularEmpledoXDeptoView consultarEmpleXDepto;
    Inicio inicio;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        mostrarInicio();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        contenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEmpleados = new javax.swing.JMenu();
        menuEmpleado = new javax.swing.JMenuItem();
        empleadosDepto = new javax.swing.JMenuItem();
        Jmenu2 = new javax.swing.JMenu();
        menuDepartamentos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuInicio = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedor.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        menuEmpleados.setText("Empleados");

        menuEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuEmpleado.setText("Administrar");
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuEmpleado);

        empleadosDepto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        empleadosDepto.setText("ConsultarEmpleadoXDepto");
        empleadosDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosDeptoActionPerformed(evt);
            }
        });
        menuEmpleados.add(empleadosDepto);

        jMenuBar1.add(menuEmpleados);

        Jmenu2.setText("Departamentos");
        Jmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmenu2ActionPerformed(evt);
            }
        });

        menuDepartamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuDepartamentos.setText("Administrar");
        menuDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepartamentosActionPerformed(evt);
            }
        });
        Jmenu2.add(menuDepartamentos);

        jMenuBar1.add(Jmenu2);

        jMenu2.setText("Opciones");

        menuInicio.setText("Inicio");
        menuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioActionPerformed(evt);
            }
        });
        jMenu2.add(menuInicio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
        empleadosView = new EmpleadosView();
        empleadosView.setVisible(true);
        empleadosView.setSize(contenedor.getWidth(),contenedor.getHeight());
        contenedor.removeAll();
        contenedor.add(empleadosView);
        
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    private void menuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioActionPerformed
        mostrarInicio();
    }//GEN-LAST:event_menuInicioActionPerformed

    private void Jmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jmenu2ActionPerformed

    private void menuDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepartamentosActionPerformed
        departamentosView = new DepartamentosView();
        departamentosView.setVisible(true);
        departamentosView.setSize(contenedor.getWidth(),contenedor.getHeight());
        contenedor.removeAll();
        contenedor.add(departamentosView);
    }//GEN-LAST:event_menuDepartamentosActionPerformed

    private void empleadosDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosDeptoActionPerformed
        consultarEmpleXDepto = new ConsularEmpledoXDeptoView();
        consultarEmpleXDepto.setVisible(true);
        consultarEmpleXDepto.setSize(contenedor.getWidth(),contenedor.getHeight());
        contenedor.removeAll();
        contenedor.add(consultarEmpleXDepto);
    }//GEN-LAST:event_empleadosDeptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenu2;
    private javax.swing.JDesktopPane contenedor;
    private javax.swing.JMenuItem empleadosDepto;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuDepartamentos;
    private javax.swing.JMenuItem menuEmpleado;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenuItem menuInicio;
    // End of variables declaration//GEN-END:variables

    private void mostrarInicio() {
        inicio = new Inicio();
        inicio.setVisible(true);
        inicio.setSize(contenedor.getWidth(),contenedor.getHeight());
        contenedor.removeAll();
        contenedor.add(inicio);
    }
}
